### ISSUE TITLE
Issue with training model on multiple folders of image sequences and their corresponding annotations

### ISSUE THREAD

**Issue by Jordan-Pierce** [VIAME/VIAME#159]
Hi, I import multiple folders of image sequences and their annotations so that all could be added to the training set for model building. When running the training on the default detection, I got to this point and received an error. Not sure what's going on here; I notice that the cocodict for the validation set (see error) is referred to `vali`; I don't think that is the problem, but maybe it is. Thoughts?

```python

config = {
    'allow_unicode': False,
    'anchors': 'auto',
    'arch': 'cascade',
    'augment': 'medium',
    'backbone_init': 'C:/VIAME/configs/pipelines/models/pytorch_resnext101.pth',
    'balance': None,
    'batch_size': 4,
    'bstep': 4,
    'channels': 'rgb',
    'classes_of_interest': [],
    'collapse_classes': False,
    'datasets': None,
    'decay': 0.0001,
    'draw_interval': 1,
    'draw_per_batch': 8,
    'dump_tensorboard': True,
    'eager_dump_tensorboard': True,
    'ensure_background_class': False,
    'focus': 0.0,
    'fuse_method': 'cat',
    'grad_norm_max': 35,
    'grad_norm_type': 2,
    'gravity': 0.0,
    'ignore_first_epochs': 2,
    'init': 'noop',
    'input_dims': 'window',
    'lr': 0.001,
    'max_epoch': 50,
    'min_lr': 1e-09,
    'multiscale': False,
    'name': 'viame-netharn-detector',
    'nice': 'viame-netharn-detector',
    'normalize_inputs': True,
    'num_batches': 'auto',
    'num_draw': 4,
    'num_vali_batches': 'auto',
    'optim': 'sgd',
    'ovthresh': 0.5,
    'patience': 16,
    'pretrained': None,
    'sampler_backend': None,
    'sampler_workdir': 'deep_training',
    'schedule': 'ReduceLROnPlateau-p2-c2',
    'seen_thresh': 12800,
    'segmentation_bootstrap': None,
    'sql_cache_view': False,
    'test_dataset': None,
    'test_on_finish': False,
    'timeout': 604800,
    'train_dataset': 'deep_training\\training_truth.json',
    'vali_dataset': 'deep_training\\validation_truth.json',
    'vali_intervals': 1,
    'warmup_iters': 800,
    'warmup_ratio': 0.1,
    'window_dims': [640, 640],
    'window_overlap': 0.2,
    'with_mask': True,
    'workdir': 'deep_training',
    'workers': 4,
    'xpu': 0,
}
[ndsampler.coerce_data] Checking for explicit subsets

tic("read kwcoco dataset: fpath = 'deep_training\\\\training_truth.json'")
...toc("read kwcoco dataset: fpath = 'deep_training\\\\training_truth.json'")=0.0318s
building kwcoco index

tic("read kwcoco dataset: fpath = 'deep_training\\\\validation_truth.json'")
...toc("read kwcoco dataset: fpath = 'deep_training\\\\validation_truth.json'")=0.0151s
Traceback (most recent call last):
  File "C:\VIAME\lib\python3.6\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\VIAME\lib\python3.6\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\VIAME\lib\python3.6\site-packages\bioharn\detect_fit.py", line 1318, in <module>
    fit()
  File "C:\VIAME\lib\python3.6\site-packages\bioharn\detect_fit.py", line 1207, in fit
    harn = setup_harn(**kw)
  File "C:\VIAME\lib\python3.6\site-packages\bioharn\detect_fit.py", line 876, in setup_harn
    cat_mapping = catid_compat_mapping(classes1, classes2)
  File "C:\VIAME\lib\python3.6\site-packages\bioharn\detect_fit.py", line 843, in catid_compat_mapping
    assert max(map(len, norm_to_names1.values())) == 1
AssertionError
building kwcoco index
[ndsampler.coerce_data] base = None
coco_datasets = {
    'train': <CocoDataset(tag=training_truth.json, n_anns=660, n_imgs=291, n_videos=0, n_cats=19) at 0x1b02eccaeb8>,
    'vali': <CocoDataset(tag=validation_truth.json, n_anns=2, n_imgs=2, n_videos=0, n_cats=19) at 0x1b02eaa6320>,
}
Process exited with code 3221225477: C:\Windows\system32\cmd.exe

```

**Comment by Jordan-Pierce** [comment]
I was able to get training to work using the YOLO 640 option.

**Comment by Erotemic** [comment]
To respond to the original issue: Looks like the issue is that `norm_to_names1` has multiple category names assigned to the same normalized value. Are the category names between your training kwcoco and validation kwcoco files different? If you have the `kwcoco` module installed you can use `kwcoco stats <path-to-kwcoco-file>` to look at the category names in each json file (or just open the file up and look at the items in the category dictionary).
