### ISSUE TITLE
Error when running plugin_explorer in Viame with Linux

### ISSUE THREAD

**Issue by abourbou** [VIAME/VIAME#173]
I tried to run ./pluging explorer in Viame0.20.2 and compiled master version on Ubuntu 20.04.
```
source ./setup_viame.sh && ./bin/plugin_explorer --algo train_detector -d


INFO: Could not load default logger factory. Using built-in logger.
Error processing line 1 of /home/arthur/.local/lib/python3.8/site-packages/sphinxcontrib_devhelp-1.0.2-py3.8-nspkg.pth:

Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/site.py", line 168, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/importlib/__init__.py", line 51, in <module>
    _w_long = _bootstrap_external._w_long
AttributeError: module 'importlib._bootstrap_external' has no attribute '_w_long'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/site.py", line 556, in <module>
    main()
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/site.py", line 542, in main
    known_paths = addusersitepackages(known_paths)
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/site.py", line 285, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/site.py", line 178, in addpackage
    import traceback
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/re.py", line 123, in <module>
    import sre_compile
  File "/home/arthur/Desktop/Software/Viame_0.20.2/lib/python3.6/sre_compile.py", line 17, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
AssertionError: SRE module mismatch
```

**Comment by abourbou** [comment]
Ok sorry, I made it work by sourcing in my terminal and then launch the command.
I still got some minor error messages :
```
2024-02-20 10:47:34.673 INFO plugin_loader.cxx(362): plugin_loader:: Unable to bind to function "register_factories()" : /home/arthur/Desktop/Software/Viame_0.20.2/bin/../lib/kwiver/plugins/plugin_explorer/algo_explorer_plugin.so: undefined symbol: register_factories
2024-02-20 10:47:34.674 INFO plugin_loader.cxx(362): plugin_loader:: Unable to bind to function "register_factories()" : /home/arthur/Desktop/Software/Viame_0.20.2/bin/../lib/kwiver/plugins/plugin_explorer/cluster_explorer_plugin.so: undefined symbol: register_factories
2024-02-20 10:47:34.675 INFO plugin_loader.cxx(362): plugin_loader:: Unable to bind to function "register_factories()" : /home/arthur/Desktop/Software/Viame_0.20.2/bin/../lib/kwiver/plugins/plugin_explorer/process_explorer_plugin.so: undefined symbol: register_factories
2024-02-20 10:47:34.675 WARN plugin_explorer.cxx(293): Formatting type "" for category "process" not available.
  Plugin name: frame_list_input
      Reads a list of image file names and generates stream of images and
      associated time stamps.
2024-02-20 10:47:34.675 WARN plugin_explorer.cxx(293): Formatting type "" for category "process" not available.
  Plugin name: detected_object_input
      Reads detected object sets from an input file.
      
      Detections read from the input file are grouped into sets for each image
      and individually returned.
2024-02-20 10:47:34.675 WARN plugin_explorer.cxx(293): Formatting type "" for category "process" not available.
  Plugin name: video_input
      Reads video files and produces sequential images with metadata per frame.
2024-02-20 10:47:34.675 WARN plugin_explorer.cxx(293): Formatting type "" for category "process" not available.
  Plugin name: input_adapter
      Source process for embedded pipeline.
      
      Pushes data items into pipeline ports. Ports are dynamically created as
      needed based on connections specified in the pipeline file

```
